jake/ossindex/ossindex.py
jake/parse/parse.py
jake/test_ossindex.py
jake/test_parse.py

Chunking requests to OSSIndex and fixing tests because of the change
Changes made:
* Request to OSSIndexs now have no more than 128 purls (limit set by OSSIndex)
* Tests fixed as a result of above change

Chunking requests and fixing tests

---

.circleci/ci-run.sh
.circleci/ci-setup.sh

The CI scripts should stop with an error whenever some command fails (rather than plunging ahead after errors).
I'm still trying to figure out why the linter seems to behave differently locally vs ci...

Make CI scripts fail on any error

---

jake/__main__.py
jake/config/config.py
jake/config/iq_config.py
jake/cyclonedx/v1_1/generator.py
jake/iq/iq.py
jake/ossindex/ossindex.py
jake/test/test_config.py
jake/test/test_iq_config.py
jake/types/results_decoder.py
jake/types/vulnerabilities.py
requirements.txt

Because who doesn't like yaml?!?!
Seriously though we are starting to save OSS Index config in a few tools, so why not use yaml, and a common location, so they can all pick it up. 
* Adds PyYAML
* Implements yaml load and dump in base config class
* Also moves config by default to it's own `.ossindex` folder
cc @bhamail / @DarthHater / @allenhsieh

Yaml for Config

---

jake/cyclonedx/v1_1/generator.py

Refactor vulnerability validation to a specific method: validate_xml_vulnerabilities()
Existing generic method (validate_xml()) is not used, is unchanged, and can be improved later.
No change to behavior in this PR.

refactor to use explicit validate_xml_vulnerabilities() method

---

.circleci/ci-publish.sh
jake/__main__.py
setup.py

Creates the directory of the path that gets passed in for the sbom output if it doesn't exist
Also handled permission errors for when the python shell can't create it
Should work in windows since it uses os.path for everything but still need to test
* Fixes #23 
cc @bhamail / @DarthHater / @maurycupitt

Sbom mkdir if it doesn't exist and error handling

---

.gitignore
jake/audit/audit.py
requirements.txt

Okie dokie, based on some best practices from user testing, now we have dependencies grouped by if they are vulnerable or not vulnerable.
Vulnerabilities output in a table, and a summary is shown at the end.
Fixes #29 

Group good 'n' bad vulnerabilities and output them in tables

---

jake/ossindex/ossindex.py
jake/test/test_ossindex.py
requirements.txt

Basically six is causing a collision due to how we include it, so I wondered if we could just drop deps that need it, and this was the outcome!
* Removes unused libs from `requirements.txt`
* Removes `python-dateutil` by switching to using `datetime` and `strptime`
* Fixes #X

Drop six as a dependency

---

README.md
jake/__main__.py
jake/iq/iq.py

This PR allows insecure requests to be made (only to IQ Server, we generally know OSS Index should be secure)
* Adds a `-i` or `--insecure` flag to the `iq` command
* Modifies the IQ server class to be a bit "better", setting up a shared session, and setting config on it where we know it's global

Allow insecure requests

---

jake/__main__.py
jake/test/iqpolicywarningresponse.txt
jake/test/test_iq.py

IQ Rest API can return a `Warning` policyAction value. This PR handles that case. A `Warning` will not return an error status code.

Handle IQ warning

---

jake/cyclonedx/v1_1/generator.py
jake/test/test_sbom_generator.py

remove any `?` parameter suffix from the `version` value shown in the generated sbom.
For example, a purl with: `pkg:pypi/yaspin@0.16.0?extension=tar.gz` will now produce an sbom version: `0.16.0`.
Prior to this fix, the version would include the parameter suffix like so: `0.16.0?extension=tar.gz`
Verified that non-suffixed purl still produces a proper version. e.g; purl: `pkg:pypi/normalpurl@0.17.0` produces version `0.17.0`.
* Fixes #43

remove extension parameter suffix from sbom 'version' tag. 

---

jake/__main__.py
jake/iq/iq.py
jake/test/iqresponse_absolute_report_url.json
jake/test/iqresponse_relative_report_url.json
jake/test/test_iq.py
jake/test/test_main.py

Newer versions of IQ (104+) respond with a relative report URL. This PR ensures an absolute report url will be shown to the user, regardless of which IQ version is being used.
Also tweaks the coloring of the display.
1. It used to leave the console set to whatever color was last printed. Now resets console color.
2. Tweaked colors of for policy actions:

use an absolute report url (handle IQ 104+)

---

README.md
jake/__main__.py

added example to readme of site-packages target list generation in-line to the flag argument
I figured out a simpler way to specify site packages targets as shown below without having to save the output to an env var and pass it in:
```
artie@ArtieSonaDell:~$ source .venv/bin/activate
(.venv) artie@ArtieSonaDell:~$ jake ddt -t "`python -c "import site; print(site.getsitepackages())"`"
___           ___           ___
___        /  /\         /  /\         /  /\
/__/\      /  /::\       /  /:/        /  /::\
\__\:\    /  /:/\:\     /  /:/        /  /:/\:\
___ /  /::\  /  /::\ \:\   /  /::\____   /  /::\ \:\
/__/\  /:/\/ /__/:/\:\_\:\ /__/:/\:::::\ /__/:/\:\ \:\
\  \:\/:/~~  \__\/  \:\/:/ \__\/~|:|~~~~ \  \:\ \:\_\/
\  \::/          \__\::/     |  |:|      \  \:\ \:\
\__\/           /  /:/ …
```

Inline targets help changes

---

README.md
jake/__main__.py
jake/audit/audit.py
jake/pip/pip.py

Currently `ddt` can only print output in human readable format. This PR adds the option to print found vulnerabilities only in JSON format.
* Adds `-o, --output-format` flag for `ddt` command

Add json output format for ddt command

---

requirements.txt

Our internal Jenkins CI build was seeing errors like the one below:
```
ERROR [0.000s]: jake.test.test_main (unittest.loader._FailedTest)
2021-06-28 14:04:01 GMT-04:00  ----------------------------------------------------------------------
2021-06-28 14:04:01 GMT-04:00  ImportError: Failed to import test module: jake.test.test_main
2021-06-28 14:04:01 GMT-04:00  Traceback (most recent call last):
2021-06-28 14:04:01 GMT-04:00    File "/usr/local/lib/python3.7/unittest/loader.py", line 436, in _find_test_path
2021-06-28 14:04:01 GMT-04:00      module = self._get_module_from_name(name)
2021-06-28 14:04:01 GMT-04:00    File "/usr/local/lib/python3.7/unittest/loader.py", line 377, in _get_module_from_name
2021-06-28 14:04:01 GMT-04:00      __import__(name)
2021-06-28 14:04:01 GMT-04:00 …
```

fix: "ModuleNotFoundError: No module named 'typing_extensions'"

---

requirements.txt

resolve vulnerability: CVE-2021-33503 in urllib3 == 1.26.4 detected via OSSI

fix: CVE-2021-33503 in urllib3 == 1.26.4

---

poetry.lock
pyproject.toml

fix: bump required version of cyclonedx-python-lib to help lax transitive dependencies

---

.pre-commit-hooks.yaml
README.md

I've added a simple pre-commit hook to be used to launch an OSS-backed ddt scan
* Adds a pre-commit hook
* Documents a simple use of the hook
* Fixes #84 

feat(pre-commit): add pre-commit hooks

---

jake/command/oss.py
poetry.lock
pyproject.toml

fix:`bom-ref` will always now be populated for Component and Vulnerability - bump of `cyclonedx-python-lib` resolves this
fix: complete `affects` for vulnerabilities received from OSS Index
* Fixes #91 

fix: `bom-ref` will always now be populated for Component and Vulnerability

---

jake/command/oss.py

* Correctly parse CWE references to `int` values as required by CDX model
* Fixes #95

fix: CWEs not passed as ints to CDX model

---

jake/command/oss.py

fix: Vulnerability rating score now formatted to 1 decimal place
* Fixes #98 

fix: CWEs are `int` and needed to be stringified

---

poetry.lock
pyproject.toml

Some upstream dependencies have release candidates (RCs) for next major versions which break the current version of `jake`.
This PR looks to prevent these newer versions from being used with `jake`.
* Fixes #112 

fix: pin some upstream dependencies to prevent #112

---

.circleci/config.yml

Try a filter to prevent `manual_release` job from running on feature branches

prevent manual_release job on non-main branches. partial fix for #108

---

.circleci/config.yml
README.md
docs/usage.rst
jake/command/iq.py
jake/command/oss.py
jake/command/parser_selector.py
jake/command/sbom.py

- refactor `SbomCommand._get_parser()` method into a function in its own `parser_selector` module
- move the two needed argparse arguments to `add_parser_selector_arguments` function in the same module
- use those function in both `ddt` and `iq` commands.
BREAKING CHANGE: changed iq -i switch to -a, removed sbom -t switch (only -it works)
* Closes #104

feat: Support for all input formats when running jake ddt or jake iq

---

README.md

examples in README.md were still using the `-i` flag instead of `-f`. Fixed.

docs: fix -f switch in the examples

---

.github/CONTRIBUTORS.md
jake/command/oss.py

Handles the case where CWE name == `CWE-noinfo`
It relates to the following issue :
* Fixes #128

fix: handle CWE name suffixed with 'noinfo'

---

pyproject.toml
requirements.lowest.txt

upgrade lowest to ossindex-lib 1.1.1, which appears to allow newer PyYAML (6+), which fixes cython_sources error when building PyYAML 5.4.1

Fix cython_sources build error

---

jake-whitelist.json
pyproject.toml

* changes rich ^10.10.0 to rich >=10.10.0
(If there are changes to user behavior in general, please make sure to
update the docs, as well)
* Addressing issues #127 #143

Update pyproject.toml - allow higher rich version

---

.circleci/config.yml

See #147
* add twine upload to circleci
* update usage of python-semantic-release to support v8 https://python-semantic-release.readthedocs.io/en/latest/migrating_from_v7.html
* See thread on #147

Update circleci config.yml
